const { getPrediction } = require('../services/mlService');
const Prediction = require('../../models/predictions.model');
const Alert = require('../../models/alerts.model');
const Slope = require('../../models/slopes.model');
const { getDatabaseStatus } = require('../config/db');

const predictionFields = [
  'Rainfall_mm', 'Rainfall_3Day', 'Rainfall_7Day', 'Slope_Angle', 'Elevation_m',
  'Soil_Saturation', 'Historical_Landslide_Count', 'Pore_Water_Pressure_kPa',
  'Soil_Moisture_Content', 'Microseismic_Activity', 'Acoustic_Emission_dB',
  'Soil_Strain', 'Soil_Erosion_Rate', 'NDVI_Index', 'Vegetation_Cover',
  'Distance_to_Road_m', 'Proximity_to_Water', 'Earthquake_Activity', 'TDR_Reflection_Index',
];

async function persistPrediction(inputFeatures, slopeId, data) {
  if (getDatabaseStatus() !== 'CONNECTED') {
    console.warn('Prediction persistence skipped: MongoDB is not connected.');
    return null;
  }

  try {
    const prediction = await Prediction.create({
      slopeId: slopeId || 'UNASSIGNED',
      source: data.source || 'ml-service',
      modelVersion: data.modelVersion || 'xgboost-v1',
      inputFeatures: { ...inputFeatures },
      prediction: data.prediction,
      riskProbability: data.risk_probability,
      riskScore: data.risk_score,
      riskLevel: data.risk_level,
      createdAt: new Date(),
    });
    console.log('Prediction persisted successfully.');
    return prediction;
  } catch (error) {
    console.error(`Prediction persistence failed: ${error.message}`);
    return null;
  }
}

async function persistAlert(prediction, slopeId, data) {
  if (!prediction || !slopeId || !['HIGH', 'CRITICAL'].includes(data.risk_level)) return;
  try {
    const now = new Date();
    const title = `${data.risk_level === 'CRITICAL' ? 'Critical' : 'High'} Landslide Risk Detected – ${slopeId}`;
    const message = `${slopeId} received an AI risk score of ${Number(data.risk_score).toFixed(1)} (${data.risk_level}). Generated by the prototype ML prediction system.`;
    const activeAlert = await Alert.findOne({ slopeId, severity: data.risk_level, status: 'ACTIVE' });
    if (activeAlert) {
      activeAlert.predictionId = prediction._id;
      activeAlert.title = title;
      activeAlert.message = message;
      activeAlert.riskScore = data.risk_score;
      activeAlert.updatedAt = now;
      await activeAlert.save();
      return;
    }
    await Alert.create({
      alertId: `AL-${slopeId}-${Date.now()}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`,
      slopeId,
      predictionId: prediction._id,
      severity: data.risk_level,
      title,
      message,
      riskScore: data.risk_score,
      status: 'ACTIVE',
      createdAt: now,
      updatedAt: now,
    });
  } catch (error) {
    console.error(`Alert persistence failed: ${error.message}`);
  }
}

async function predict(req, res, next) {
  const input = req.body || {};
  if (input.slopeId !== undefined && (typeof input.slopeId !== 'string' || !input.slopeId.trim())) {
    const error = new Error('Invalid slopeId: expected a non-empty string');
    error.statusCode = 400;
    error.isOperational = true;
    return next(error);
  }
  const missingFields = predictionFields.filter((field) => !(field in input));
  const invalidFields = predictionFields.filter(
    (field) => field in input && (typeof input[field] !== 'number' || !Number.isFinite(input[field])),
  );

  if (missingFields.length || invalidFields.length) {
    const details = [];
    if (missingFields.length) details.push(`missing fields: ${missingFields.join(', ')}`);
    if (invalidFields.length) details.push(`invalid numeric fields: ${invalidFields.join(', ')}`);
    const error = new Error(`Invalid prediction input (${details.join('; ')})`);
    error.statusCode = 400;
    error.isOperational = true;
    return next(error);
  }

  const orderedInput = Object.fromEntries(predictionFields.map((field) => [field, input[field]]));
  try {
    if (input.slopeId) {
      if (getDatabaseStatus() !== 'CONNECTED') {
        const error = new Error('Database service is currently unavailable to validate slopeId');
        error.statusCode = 503;
        error.isOperational = true;
        return next(error);
      }
      const slope = await Slope.exists({ slopeId: input.slopeId.trim() });
      if (!slope) {
        const error = new Error(`Slope not found: ${input.slopeId}`);
        error.statusCode = 400;
        error.isOperational = true;
        return next(error);
      }
    }
    const data = await getPrediction(orderedInput);
    void persistPrediction(orderedInput, input.slopeId, data).then((prediction) => persistAlert(prediction, input.slopeId?.trim(), data));
    return res.json({ success: true, data });
  } catch (error) {
    return next(error);
  }
}

module.exports = { predict };
